"""Turns the setup HTML pages into PROGMEM strings the firmware can serve.

The pages are the source of truth: edit the HTML and the headers are regenerated
on the next build. Nothing else needs touching, which is why this runs pre-build
instead of the headers being committed.

Two pages, because the access point comes up for two different reasons — the
first-boot walkthrough and the panel a long press opens on a board that already
works. See the comment at the top of lib/Setup/SetupPortal.h.

Wired up from platformio.ini via extra_scripts.
"""

import os

Import("env")  # noqa: F821 — injected by SCons

PROJECT_DIR = env.subst("$PROJECT_DIR")  # noqa: F821
SETUP_DIR = os.path.join(PROJECT_DIR, "lib", "Setup")

# (html source, generated header, symbol prefix)
PAGES = [
    ("bonsai-setup.html", "setup_page.h", "kSetupPage"),
    ("bonsai-panel.html", "panel_page.h", "kPanelPage"),
]

# Raw strings would be simpler, but a page is free to contain any delimiter we
# picked, so the bytes go in as escaped octal instead. 20 per line keeps the
# generated file readable in a diff without making it enormous.
PER_LINE = 20


def generate(page_name, header_name, symbol):
    page = os.path.join(PROJECT_DIR, page_name)
    header = os.path.join(SETUP_DIR, header_name)

    if not os.path.exists(page):
        raise SystemExit(
            "embed_setup_page: %s is missing; SetupPortal.cpp includes %s and "
            "will not compile without it." % (page_name, header_name))

    with open(page, "rb") as f:
        data = f.read()

    lines = []
    for i in range(0, len(data), PER_LINE):
        chunk = data[i:i + PER_LINE]
        lines.append('    "' + "".join("\\%03o" % b for b in chunk) + '"')

    text = (
        "// Generated by scripts/embed_setup_page.py — do not edit.\n"
        "// Source: %s (%d bytes)\n"
        "#pragma once\n"
        "#include <Arduino.h>\n\n"
        "constexpr size_t %sLen = %d;\n\n"
        "const char %s[] PROGMEM =\n%s;\n"
    ) % (page_name, len(data), symbol, len(data), symbol, "\n".join(lines))

    # Only rewrite when it actually changed, so an unchanged page does not force
    # every translation unit that includes it to recompile.
    if os.path.exists(header):
        with open(header, "r", encoding="utf-8") as f:
            if f.read() == text:
                return

    os.makedirs(SETUP_DIR, exist_ok=True)
    with open(header, "w", encoding="utf-8") as f:
        f.write(text)
    print("embed_setup_page: %s -> %s (%d bytes)" % (page_name, header_name,
                                                     len(data)))


for args in PAGES:
    generate(*args)
